# YOLO Dataset Configuration - Skenario A (Original Citra Mentah / Splits)
path: c:/MyPrograms/swallow_detection/data/splits

train: train/images
val: val/images
test: test/images

nc: 1
names:
  0: walet
